# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20171108_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='newsletter_subscription_active',
            field=models.BooleanField(default=False),
        ),
    ]
