# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_profile_newsletter_subscription_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnonymousUser',
        ),
        migrations.AddField(
            model_name='morsel',
            name='public_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
